{% set version = "1.14.3" %}
{% set abi_version = "1.0" %}

package:
  name: cairomm
  version: {{ version }}

source:
  url: https://www.cairographics.org/releases/cairomm-{{ version }}.tar.xz
  sha256: 0d37e067c5c4ca7808b7ceddabfe1932c5bd2a750ad64fb321e1213536297e78

build:
  number: 0
  run_exports:
    - cairomm-{{ abi_version }} >={{ version }}

outputs:
  - name: cairomm-{{ abi_version }}
    script: build_cairomm.sh  # [unix]
    script: build_cairomm.bat  # [win]
    build:
      run_exports:
        - cairomm-{{ abi_version }} >={{ version }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - meson
        - ninja
      host:
        - cairo  >=1.12.0
        - sigcpp-2.0  >=2.6.0
      run_constrained:
        - cairomm {{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libcairomm-{{ abi_version }}${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_BIN%\\cairomm-{{ abi_version }}-0.dll exit 1  # [win]

  - name: cairomm
    requirements:
      run:
        - cairomm-{{ abi_version }}  {{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/pkg-config/cairomm-{{ abi_version }}.pc  # [unix]
        - if not exist %LIBRARY_LIB%\\pkgconfig\\cairomm-{{ abi_version }}.pc exit 1  # [win]

about:
  home: http://cairographics.org/
  license: LGPL-2.1-or-later and MPL-1.1
  license_file: COPYING
  summary: "cairomm is a C++ wrapper for the cairo graphics library"

extra:
  recipe-maintainers:
    - vgauthier
    - isuruf
