{% set version = "1.15.5" %}
{% set abi_version = "1.0" %}

package:
  name: cairomm
  version: {{ version }}

source:
  url: https://www.cairographics.org/releases/cairomm-{{ version }}.tar.gz
  sha256: 8db629f44378cac62b4931f725520334024e62c1951c4396682f1add63c1e3d1

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - cairomm-{{ abi_version }} >={{ version }}

outputs:
  - name: cairomm-{{ abi_version }}
    script: build_cairomm.sh
    build:
      run_exports:
        - cairomm-{{ abi_version }} >={{ version }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - pkg-config
        - make
      host:
        - libpng
        - zlib
        - freetype
        # These requirements can be found in configure.ac
        - glib
        - cairo
        - sigcpp-2.0  >=2.5.1
      run_constrained:
        - cairomm {{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libcairomm-{{ abi_version }}${SHLIB_EXT}

  - name: cairomm
    requirements:
      run:
        - cairomm-{{ abi_version }}  {{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/pkg-config/cairomm-{{ abi_version }}.pc

about:
  home: http://cairographics.org/
  license: LGPL-2.1-or-later and MPL-1.1
  license_file: COPYING
  summary: cairomm is a C++ wrapper for the cairo graphics library

extra:
  recipe-maintainers:
    - vgauthier
    - isuruf
