{% set version = "1.16.2" %}
{% set abi_version = "1.16" %}

package:
  name: cairomm
  version: {{ version }}

source:
  url: https://www.cairographics.org/releases/cairomm-{{ version }}.tar.xz
  sha256: 6a63bf98a97dda2b0f55e34d1b5f3fb909ef8b70f9b8d382cb1ff3978e7dc13f

build:
  number: 0
  run_exports:
    - cairomm-{{ abi_version }} >={{ version }}

outputs:
  - name: cairomm-{{ abi_version }}
    script: build_cairomm.sh  # [unix]
    script: build_cairomm.bat  # [win]
    build:
      run_exports:
        - cairomm-{{ abi_version }} >={{ version }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - meson
        - ninja
        - pkg-config
      host:
        - cairo  >=1.12.0
        - sigcpp-3.0
        - glib
        - zlib
        - freetype
        - libpng
      run_constrained:
        - cairomm {{ version }}
    test:
      requires:
        - pkg-config
        - glib
        - zlib
        - freetype
        - libpng
      commands:
        - test -f ${PREFIX}/lib/libcairomm-{{ abi_version }}${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_BIN%\\cairomm-vc142-{{ abi_version }}-1.dll exit 1  # [win]
        - pkg-config --exact-version {{ version }} cairomm-{{ abi_version }}

  - name: cairomm
    requirements:
      run:
        - cairomm-{{ abi_version }}  {{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/pkg-config/cairomm-{{ abi_version }}.pc  # [unix]
        - if not exist %LIBRARY_LIB%\\pkgconfig\\cairomm-{{ abi_version }}.pc exit 1  # [win]

about:
  home: http://cairographics.org/
  license: LGPL-2.1-or-later and MPL-1.1
  license_file: COPYING
  summary: cairomm is a C++ wrapper for the cairo graphics library

extra:
  recipe-maintainers:
    - vgauthier
    - isuruf
    - tschoonj
