{% set version = "1.12.2" %}

package:
  name: cairomm
  version: {{ version }}

source:
  url: https://www.cairographics.org/releases/cairomm-{{ version }}.tar.gz
  sha256: 45c47fd4d0aa77464a75cdca011143fea3ef795c4753f6e860057da5fb8bd599

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - pkg-config
    - {{ compiler('cxx') }}
  host:
    - cairo
    - libpng
    - libsigcpp
  run:
    - cairo
    - libpng
    - libsigcpp

test:
  commands:
    - test -f ${PREFIX}/lib/libcairomm-1.0.a
    - test -f ${PREFIX}/lib/libcairomm-1.0${SHLIB_EXT}  # [not win]

about:
  home: http://cairographics.org/
  license: LGPL 2.1 and MPL 1.1
  license_file: COPYING
  summary: "cairomm is a C++ wrapper for the cairo graphics library"

extra:
  recipe-maintainers:
    - vgauthier
