# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "av5pDtalVHZEsDnb1RiwmRcOTN69FvfwqGn9AWmKPCch2MZAZzVGVazAlpMmoUySL4UuE5oFA8cmp+3mvGNnAbUcvQT28q5tUiuskW2VjKZOLv2r3ydKrjwMmzEb9JOd7XoQDrkMmNkORC0BH31JqM0/DWS5BUFzZdL2OsBxNPdzGlpQB9571529ip8tJKx45YhT9q996CPx30DoHSA2NwT6HKZdfsFSsdJwckQbKFeNOc4gh6RgPFzL/qaa7h6bMJ9TbgpDGuu8v42RPRpQVojKMleJ0qGvaN4Ln048h+5zEn4fOLJbuWvb/r8E9x8fg8H63/+HyhgEp/bDixbbsAT4FAEsRdH/el2Q+OiZpBPzQArZ/UsQVS1+b1unS9wTT4AB0QzoeBC+cfXep9pTgtFydqWoMyZrFqaIFTjJQ1J/37iL1zI50IDJ5v87YHTYT7h/Bf6DreU9hANHxB9H+TgQmn+e1R/tdWPioj3OABvtL+l6FW/+5Ep5Jl+BOMBtDBw+O3CWrl8mqq+YqMZDYB4d3QUdMs71YA3cnC2oXgerVCVgufLe/aYLZQjz7gNn0H/h6Hvj9udvtKG5SMATVX6iWmJHq/i2uPd/R2YtilWflKOy1vLMiwWBDo718y/2C/ds6J1EvR18+BKstH66XnnZVvlCZgHP/Acf0DKTKM8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
