travis:
  secure:
    BINSTAR_TOKEN: dw4VcXKiXrIC6Yo9otx3ich/vLW9fN1jfRiTVu4BPBrEP+Qsraz6s4TQteSLf3lj29euE9EUV3wVCqBQAzSpJVTjxM/Qbud3szIOplqKmdG5JM9a3BQW0MaQ7wks30SY+N9SR/9d8eiQ7zpJ/lLm3CIoGBDGdMbdhUc+OSaSlJjo31CUSLk87TKErosoohtpJklcKm9tRmOZ/WJaaIRsqXVyMXwTunYpCUqyEC9NEm5ywnMr6moGiGCKKo9ADVS7IMRH4Mdu98b//GYbufOu8jxLHvT3i4JILNBxjhP69AGLNEyMy0lodPOhXJ2yD3ke5VvWr829IBwZ+NoZkTYPm0ztpuAu+QPySNqKtkyyueyk4zlx0Jksl4/bR234Ew39W0uf12+CatlEXhwP1odKVH3ske1Qq6Lhc+r02OTF57Eu1N/XpYZIAuCzyPsvlbFF2zlcA8hIXMSBGDNaL2Y6feOod6XHYciYed4ZWOALoDfPf7hSgrPBGAYj9voLvUyoDWrh/VqRkE7mNdrY+DmjXO6A6mpmE00OyjqSAaoog6Hauh1T4/iqJm0MhYuRFvM5f7oZoeph8mFOKDTJB2xX2LrSDsIF03pFkev+t1D4589eOcmTTjqaPLk4t7zRsYnT7d+jH0qNkSoX7JznLq7gDfv9LNAFXSQ33nZcql1D+LA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
