appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: av5pDtalVHZEsDnb1RiwmRcOTN69FvfwqGn9AWmKPCch2MZAZzVGVazAlpMmoUySL4UuE5oFA8cmp+3mvGNnAbUcvQT28q5tUiuskW2VjKZOLv2r3ydKrjwMmzEb9JOd7XoQDrkMmNkORC0BH31JqM0/DWS5BUFzZdL2OsBxNPdzGlpQB9571529ip8tJKx45YhT9q996CPx30DoHSA2NwT6HKZdfsFSsdJwckQbKFeNOc4gh6RgPFzL/qaa7h6bMJ9TbgpDGuu8v42RPRpQVojKMleJ0qGvaN4Ln048h+5zEn4fOLJbuWvb/r8E9x8fg8H63/+HyhgEp/bDixbbsAT4FAEsRdH/el2Q+OiZpBPzQArZ/UsQVS1+b1unS9wTT4AB0QzoeBC+cfXep9pTgtFydqWoMyZrFqaIFTjJQ1J/37iL1zI50IDJ5v87YHTYT7h/Bf6DreU9hANHxB9H+TgQmn+e1R/tdWPioj3OABvtL+l6FW/+5Ep5Jl+BOMBtDBw+O3CWrl8mqq+YqMZDYB4d3QUdMs71YA3cnC2oXgerVCVgufLe/aYLZQjz7gNn0H/h6Hvj9udvtKG5SMATVX6iWmJHq/i2uPd/R2YtilWflKOy1vLMiwWBDo718y/2C/ds6J1EvR18+BKstH66XnnZVvlCZgHP/Acf0DKTKM8=}
